width: 0.3

size: [480, 485]

spawn_pos: [0, -0.1, -0.5]

elements:
  # Background
  - type: Panel
    rect: [0, 0, 600, 544]
    corner_radius: 4
    bg_color: "#222222"

  - type: Label
    rect: [10, 35, 600, 70]
    corner_radius: 4
    font_size: 22
    fg_color: "#aaaaaa"
    source: Static
    text: "Settings"

  - type: Button
    rect: [200, 0, 80, 45]
    corner_radius: 4
    font_size: 20
    bg_color: "#f05d6b"
    fg_color: "#222222"
    text: "Exit"
    click_down:
      - type: Exec
        command: [ "pkill", "-f", "wlx-overlay-s" ]
      - type: Toast
        message: "Killing WlxOverlay"

  - type: Button
    rect: [440, 0, 40, 40]
    corner_radius: 4
    font_size: 16
    bg_color: "#f05d6b"
    fg_color: "#222222"
    text: "X"
    click_down:
      - type: Window
        target: "settings"
        action: Destroy

  - type: Panel
    rect: [10, 53, 460, 2]
    corner_radius: 4
    bg_color: "#aaaaaa"

  # Watch

  - type: Label
    rect: [10, 88, 570, 24]
    corner_radius: 4
    font_size: 18
    fg_color: "#aaaaaa"
    source: Static
    text: Watch

  - type: Button
    rect: [10, 100, 220, 35]
    corner_radius: 4
    font_size: 16
    bg_color: "#353535"
    fg_color: "#dcdcdc"
    text: "Hide"
    click_down:
      - type: Watch
        action: Hide

  - type: Button
    rect: [10, 150, 220, 35]
    corner_radius: 4
    font_size: 16
    bg_color: "#353535"
    fg_color: "#dcdcdc"
    text: "Swap Hand"
    click_down:
      - type: Watch
        action: SwitchHands

  - type: Button
    rect: [250, 100, 220, 35]
    corner_radius: 4
    font_size: 16
    bg_color: "#353535"
    fg_color: "#dcdcdc"
    text: "Cutoff Point"
    click_down:
      - type: Toast
        message: Use stick up/down while hovering the button!
    scroll_up:
      - type: Watch
        action:
          ViewAngle: { kind: "MaxOpacity", delta: 0.01 }
    scroll_down:
      - type: Watch
        action:
          ViewAngle: { kind: "MaxOpacity", delta: -0.01 }

  - type: Button
    rect: [250, 150, 220, 35]
    corner_radius: 4
    font_size: 16
    bg_color: "#353535"
    fg_color: "#dcdcdc"
    text: "Cutoff Strength"
    click_down:
      - type: Toast
        message: Use stick up/down while hovering the button!
    scroll_up:
      - type: Watch
        action:
          ViewAngle: { kind: "MinOpacity", delta: 0.01 }
    scroll_down:
      - type: Watch
        action:
          ViewAngle: { kind: "MinOpacity", delta: -0.01 }

  - type: Panel
    rect: [10, 200, 460, 2]
    corner_radius: 4
    bg_color: "#aaaaaa"

  # Behavior

  - type: Label
    rect: [10, 232, 570, 24]
    corner_radius: 4
    font_size: 18
    fg_color: "#aaaaaa"
    source: Static
    text: "Behavior"

  - type: Button
    rect: [10, 245, 220, 35]
    corner_radius: 4
    font_size: 16
    bg_color: "#353535"
    fg_color: "#dcdcdc"
    text: "Auto-Realign"
    click_down:
      - type: System
        action: ToggleAutoRealign

  - type: Button
    rect: [10, 295, 220, 35]
    corner_radius: 4
    font_size: 16
    bg_color: "#353535"
    fg_color: "#dcdcdc"
    text: "Grab+Scroll Slide"
    click_down:
      - type: System
        action: ToggleAllowSliding

  # Playspace

  - type: Label
    rect: [250, 232, 90, 24]
    corner_radius: 4
    font_size: 18
    fg_color: "#aaaaaa"
    source: Static
    text: "Playspace"

  - type: Button
    rect: [250, 245, 220, 35]
    corner_radius: 4
    font_size: 16
    bg_color: "#353535"
    fg_color: "#dcdcdc"
    text: "Fix Floor"
    click_down:
      - type: System
        action: PlayspaceFixFloor

  - type: Button
    rect: [250, 295, 220, 35]
    corner_radius: 4
    font_size: 16
    bg_color: "#353535"
    fg_color: "#dcdcdc"
    text: "Reset Offset"
    click_down:
      - type: System
        action: PlayspaceResetOffset

  - type: Panel
    rect: [10, 345, 460, 2]
    corner_radius: 4
    bg_color: "#aaaaaa"

  # Notifications

  - type: Label
    rect: [10, 378, 90, 24]
    corner_radius: 4
    font_size: 18
    fg_color: "#aaaaaa"
    source: Static
    text: "Notifications"

  - type: Button
    rect: [10, 390, 220, 35]
    corner_radius: 4
    font_size: 16
    bg_color: "#353535"
    fg_color: "#dcdcdc"
    text: "Enabled"
    click_down:
      - type: System
        action: ToggleNotifications

  - type: Button
    rect: [10, 440, 220, 35]
    corner_radius: 4
    font_size: 16
    bg_color: "#353535"
    fg_color: "#dcdcdc"
    text: "Sound Enabled"
    click_down:
      - type: System
        action: ToggleNotificationSounds

  # Saving

  - type: Label
    rect: [250, 378, 90, 24]
    corner_radius: 4
    font_size: 18
    fg_color: "#aaaaaa"
    source: Static
    text: "Saving"

  - type: Button
    rect: [250, 390, 220, 35]
    corner_radius: 4
    font_size: 16
    bg_color: "#353535"
    fg_color: "#dcdcdc"
    text: "Save Config"
    click_down:
      - type: System
        action: PersistConfig
      - type: Toast
        message: Settings saved successfully.

  - type: Button
    rect: [250, 440, 220, 35]
    corner_radius: 4
    font_size: 16
    bg_color: "#353535"
    fg_color: "#dcdcdc"
    text: "Save Layout"
    click_down:
      - type: System
        action: PersistLayout
      - type: Toast
        message: Saved. You will see this layout on next startup.

